### ISSUE TITLE
Hook Updated Articles into Review Process

### ISSUE THREAD

**Issue by hackman104** [dSHARP-CMU/archive_plugin#2]
- [x] Allow updated articles to be reviewed and approved
- [x] Should replace original article in article table of contents once approved and published

**Comment by mdlincoln** [comment]
No idea whether the 2nd part of this was ever finished 🤷‍♂️

**Comment by hachacha** [comment]
seems to be as of 992d81a81fd251f98b765378d4069c918d6d8e31
![image](https://user-images.githubusercontent.com/1020384/53896381-e86b4580-4001-11e9-9d29-30f45f208fd5.png)
v2 is the latest version of another article "Manhattan Project" which is not showing
